name: Go Build Check

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4  # Adjust the version as needed

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Project
        run: go build -v ./...
