name: Go Build and Test with Database

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4  

      - name: Install Dependencies
        run: go mod tidy

      - name: Wait for Database
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -U testuser; do
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Run All Tests
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb?sslmode=disable
        run: go test -v ./...
