name: Go Build and Test with Database

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"
      
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: defaultuser
          POSTGRES_PASSWORD: defaultpassword
          POSTGRES_DB: defaultdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U defaultuser -d defaultdb"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Dependencies
        run: go mod tidy

      - name: Wait for PostgreSQL to Start
        run: sleep 10  # Wait for PostgreSQL to be fully ready

      - name: Update PostgreSQL Credentials Securely
        run: |
          PGPASSWORD=defaultpassword psql -U defaultuser -d defaultdb -h localhost -p 5432 <<EOF
          ALTER USER defaultuser RENAME TO "${{ secrets.DB_USER }}";
          ALTER USER "${{ secrets.DB_USER }}" WITH PASSWORD '${{ secrets.DB_PASSWORD }}';
          ALTER DATABASE defaultdb RENAME TO "${{ secrets.DB_NAME }}";
          EOF

      - name: Run Tests with Database
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: localhost
          DB_PORT: "5432"
        run: go test -v ./...
